[package]
name = "metisblack-api-validation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
name = "api_validation"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
storage = { package = "metisblack-storage", path = "../storage" }
url.workspace = true

[lints]
workspace = true
